package id.antasari.sumifyai.ui.screens

import android.content.Intent
import android.net.Uri
import android.text.format.DateFormat
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.TabRowDefaults
import androidx.compose.material3.TabRowDefaults.tabIndicatorOffset
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import id.antasari.sumifyai.ui.theme.BackgroundLight
import id.antasari.sumifyai.ui.theme.BorderLight
import id.antasari.sumifyai.ui.theme.AccentPurple
import id.antasari.sumifyai.ui.components.SumifyTopAppBar
import id.antasari.sumifyai.ui.components.SumifyTopBarContentColor
import id.antasari.sumifyai.ui.theme.PrimaryIndigo
import id.antasari.sumifyai.ui.theme.SurfaceLightCard
import id.antasari.sumifyai.ui.theme.TextMuted
import id.antasari.sumifyai.ui.theme.TextPrimary
import id.antasari.sumifyai.ui.theme.TextSecondary
import id.antasari.sumifyai.ui.viewmodel.MainViewModel
import java.io.File
import java.util.Date

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DetailsScreen(
    meetingId: String,
    viewModel: MainViewModel,
    onNavigateBack: () -> Unit
) {
    val context = LocalContext.current
    val activeMeeting by viewModel.activeMeeting.collectAsState()

    var selectedTabIndex by remember { mutableStateOf(0) }

    LaunchedEffect(meetingId) {
        viewModel.startPollingMeetingStatus(meetingId)
    }

    val meeting = activeMeeting
    val dateString = remember(meeting?.createdAt) {
        if (meeting != null) {
            val date = Date(meeting.createdAt)
            DateFormat.format("dd MMMM yyyy, HH:mm", date).toString()
        } else {
            ""
        }
    }

    Scaffold(
        containerColor = BackgroundLight,
        topBar = {
            SumifyTopAppBar(
                title = { Text("Summary Details", color = SumifyTopBarContentColor, fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(imageVector = Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = SumifyTopBarContentColor)
                    }
                },
                actions = {
                    if (meeting != null && !meeting.downloadUrl.isNullOrEmpty()) {
                        IconButton(onClick = {
                            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                                type = "text/plain"
                                putExtra(Intent.EXTRA_SUBJECT, "Sumify AI Summary: ${meeting.title}")
                                putExtra(
                                    Intent.EXTRA_TEXT,
                                    "Check out this audio summary PDF for '${meeting.title}' generated by Sumify AI:\n${meeting.downloadUrl}"
                                )
                            }
                            context.startActivity(Intent.createChooser(shareIntent, "Share Summary Link"))
                        }) {
                            Icon(imageVector = Icons.Default.Share, contentDescription = "Share", tint = SumifyTopBarContentColor)
                        }
                    }
                }
            )
        }
    ) { innerPadding ->
        if (meeting == null) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Text("Loading details...", color = TextSecondary)
            }
        } else {
            val isCancelled = meeting.status.equals("cancelled", ignoreCase = true)
            val audioFileInfo = remember(
                meeting.audioFileName,
                meeting.audioFileSizeBytes,
                meeting.localAudioPath
            ) {
                if (!meeting.audioFileName.isNullOrBlank() || meeting.audioFileSizeBytes != null) {
                    AudioFileInfo(
                        name = meeting.audioFileName ?: "Audio file",
                        size = meeting.audioFileSizeBytes?.let(::formatFileSize) ?: "-"
                    )
                } else {
                    meeting.localAudioPath?.let { path ->
                        val file = File(path)
                        AudioFileInfo(
                            name = file.name.takeIf { it.isNotBlank() } ?: "Audio file",
                            size = if (file.exists()) formatFileSize(file.length()) else "File tidak tersedia"
                        )
                    }
                }
            }

            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
                    .padding(horizontal = 20.dp)
            ) {
                // Header Details
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 12.dp)
                        .border(BorderStroke(1.dp, BorderLight), RoundedCornerShape(16.dp)),
                    colors = CardDefaults.cardColors(containerColor = SurfaceLightCard),
                    shape = RoundedCornerShape(16.dp),
                    elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text(
                            text = meeting.title,
                            fontSize = 18.sp,
                            fontWeight = FontWeight.Bold,
                            color = TextPrimary
                        )
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = dateString,
                            fontSize = 12.sp,
                            color = TextSecondary
                        )
                        if (meeting.description.isNotEmpty()) {
                            Spacer(modifier = Modifier.height(10.dp))
                            Text(
                                text = meeting.description,
                                fontSize = 13.sp,
                                color = TextSecondary,
                                lineHeight = 18.sp
                            )
                        }
                        
                        Spacer(modifier = Modifier.height(10.dp))
                        
                        DetailMetadataRow(
                            label = "Bahasa",
                            value = meeting.language.toDisplayLanguage()
                        )
                        audioFileInfo?.let { info ->
                            DetailMetadataRow(label = "Nama file", value = info.name)
                            DetailMetadataRow(label = "Ukuran file", value = info.size)
                        }
                    }
                }

                // PDF Action Area
                if (!meeting.downloadUrl.isNullOrEmpty()) {
                    Card(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(bottom = 12.dp)
                            .border(BorderStroke(1.dp, BorderLight), RoundedCornerShape(16.dp)),
                        colors = CardDefaults.cardColors(containerColor = SurfaceLightCard),
                        shape = RoundedCornerShape(16.dp),
                        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(16.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                text = if (meeting.pdfFileName.isNullOrBlank()) {
                                    "PDF Report Generated"
                                } else {
                                    "PDF Downloaded"
                                },
                                color = TextPrimary,
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp
                            )
                            if (!meeting.pdfFileName.isNullOrBlank()) {
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    text = meeting.pdfFileName ?: "",
                                    color = TextSecondary,
                                    fontSize = 12.sp
                                )
                            }
                            Spacer(modifier = Modifier.height(12.dp))
                            
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(10.dp)
                            ) {
                                Button(
                                    onClick = { viewModel.downloadPdf(meeting.id, meeting.title, meeting.downloadUrl!!) },
                                    modifier = Modifier.weight(1f),
                                    colors = ButtonDefaults.buttonColors(containerColor = PrimaryIndigo),
                                    shape = RoundedCornerShape(10.dp)
                                ) {
                                    Text(
                                        if (meeting.pdfFileName.isNullOrBlank()) "Download PDF" else "Download Again",
                                        color = Color.White,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 13.sp
                                    )
                                }
                                
                                Button(
                                    onClick = {
                                        val browserIntent = Intent(Intent.ACTION_VIEW, Uri.parse(meeting.downloadUrl))
                                        context.startActivity(browserIntent)
                                    },
                                    modifier = Modifier.weight(1f),
                                    colors = ButtonDefaults.buttonColors(containerColor = Color.Transparent),
                                    border = BorderStroke(1.dp, AccentPurple),
                                    shape = RoundedCornerShape(10.dp)
                                ) {
                                    Text("Open PDF Link", color = AccentPurple, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                                }
                            }
                        }
                    }
                }

                // Content Tabs
                TabRow(
                    selectedTabIndex = selectedTabIndex,
                    containerColor = BorderLight.copy(alpha = 0.2f),
                    indicator = { tabPositions ->
                        TabRowDefaults.SecondaryIndicator(
                            modifier = Modifier.tabIndicatorOffset(tabPositions[selectedTabIndex]),
                            color = PrimaryIndigo
                        )
                    },
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(10.dp))
                        .border(BorderStroke(1.dp, BorderLight), RoundedCornerShape(10.dp))
                ) {
                    Tab(
                        selected = selectedTabIndex == 0,
                        onClick = { selectedTabIndex = 0 },
                        text = { Text("AI Summary", fontWeight = FontWeight.Bold, color = if (selectedTabIndex == 0) PrimaryIndigo else TextSecondary) }
                    )
                    Tab(
                        selected = selectedTabIndex == 1,
                        onClick = { selectedTabIndex = 1 },
                        text = { Text("Full Transcript", fontWeight = FontWeight.Bold, color = if (selectedTabIndex == 1) PrimaryIndigo else TextSecondary) }
                    )
                }

                Spacer(modifier = Modifier.height(12.dp))

                // Tab Content Body with Markdown Rendering
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .weight(1f)
                        .padding(bottom = 16.dp)
                        .background(SurfaceLightCard, RoundedCornerShape(16.dp))
                        .border(BorderStroke(1.dp, BorderLight), RoundedCornerShape(16.dp))
                        .padding(16.dp)
                ) {
                    val scrollState = rememberScrollState()
                    Column(
                        modifier = Modifier
                            .fillMaxSize()
                            .verticalScroll(scrollState)
                    ) {
                        if (selectedTabIndex == 0) {
                            val summary = meeting.summaryText
                            if (summary.isNullOrBlank()) {
                                Text(
                                    text = if (isCancelled) {
                                        "Summary ini telah dibatalkan. Tidak ada AI summary yang dibuat untuk report ini."
                                    } else {
                                        "AI summary content is generating or empty."
                                    },
                                    color = TextMuted,
                                    fontSize = 13.sp
                                )
                            } else {
                                MarkdownText(text = summary)
                            }
                        } else {
                            val transcript = meeting.transcriptExcerpt
                            if (transcript.isNullOrBlank()) {
                                Text(
                                    text = if (isCancelled) {
                                        "Summary ini telah dibatalkan sebelum proses transkripsi selesai."
                                    } else {
                                        "Full transcription is generating or empty."
                                    },
                                    color = TextMuted,
                                    fontSize = 13.sp
                                )
                            } else {
                                Text(
                                    text = transcript,
                                    color = TextSecondary,
                                    fontSize = 13.sp,
                                    lineHeight = 20.sp
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun DetailMetadataRow(
    label: String,
    value: String
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(top = 6.dp),
        verticalAlignment = Alignment.Top
    ) {
        Text(
            text = "$label:",
            color = TextMuted,
            fontSize = 12.sp,
            fontWeight = FontWeight.Medium,
            modifier = Modifier.width(86.dp)
        )
        Text(
            text = value,
            color = TextPrimary,
            fontSize = 12.sp,
            fontWeight = FontWeight.SemiBold,
            lineHeight = 17.sp,
            modifier = Modifier.weight(1f)
        )
    }
}

private data class AudioFileInfo(
    val name: String,
    val size: String
)

private fun String.toDisplayLanguage(): String {
    return when (lowercase()) {
        "id" -> "Indonesia"
        "en" -> "English"
        "auto" -> "Auto Detect"
        else -> replaceFirstChar { char ->
            if (char.isLowerCase()) char.titlecase() else char.toString()
        }
    }
}

private fun formatFileSize(bytes: Long): String {
    if (bytes <= 0L) return "0 KB"

    val kb = bytes / 1024.0
    val mb = kb / 1024.0

    return if (mb >= 1.0) {
        String.format("%.1f MB", mb)
    } else {
        String.format("%.0f KB", kb)
    }
}

@Composable
fun MarkdownText(text: String) {
    val lines = text.split("\n")
    Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
        lines.forEach { line ->
            val trimmed = line.trim()
            when {
                trimmed.startsWith("# ") -> {
                    Text(
                        text = trimmed.substring(2),
                        fontSize = 18.sp,
                        fontWeight = FontWeight.Bold,
                        color = PrimaryIndigo,
                        modifier = Modifier.padding(vertical = 4.dp)
                    )
                }
                trimmed.startsWith("## ") -> {
                    Text(
                        text = trimmed.substring(3),
                        fontSize = 15.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextPrimary,
                        modifier = Modifier.padding(vertical = 3.dp)
                    )
                }
                trimmed.startsWith("- ") || trimmed.startsWith("* ") -> {
                    Row(modifier = Modifier.padding(start = 8.dp)) {
                        Text(text = "•", color = PrimaryIndigo, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(text = trimmed.substring(2), color = TextSecondary, fontSize = 13.sp, lineHeight = 18.sp)
                    }
                }
                trimmed.isNotEmpty() -> {
                    Text(
                        text = trimmed,
                        fontSize = 13.sp,
                        color = TextSecondary,
                        lineHeight = 19.sp
                    )
                }
                else -> {
                    Spacer(modifier = Modifier.height(4.dp))
                }
            }
        }
    }
}
